#!/usr/bin/env bash
set -euo pipefail

scripts=()
while IFS= read -r -d '' f; do
	read -r first_line <"$f" || continue
	[[ "$first_line" =~ ^#![[:space:]]*/.*(ba)?sh ]] || continue
	scripts+=("$f")
done < <(
	find "$PROJECT_ROOT" \
		\( \
		-path '*/.git/*' \
		-o -path '*/.direnv/*' \
		-o -path '*/.terraform/*' \
		\) -prune -o \
		-type f -print0
)

if ((${#scripts[@]})); then
	shfmt -w "${scripts[@]}"
fi
