#!/usr/bin/env bash
shopt -s globstar nullglob
scripts=()
for f in "$DEVENV_ROOT"/**/*.sh "$DEVENV_ROOT"/**/scripts/*; do
	[[ -f "$f" ]] && scripts+=("$f")
done
if ((${#scripts[@]})); then
	shellcheck "${scripts[@]}"
	shfmt -d "${scripts[@]}"
fi
