#! /usr/bin/env bash
set -euo pipefail

echo "Checking OpenTofu formatting..."
tofu fmt -check -recursive "$DEVENV_ROOT"
echo "All files formatted correctly."

echo "Checking OpenTofu linting..."
tflint --chdir="$DEVENV_ROOT" --init
tflint --chdir="$DEVENV_ROOT" --recursive
echo "tflint passed."

echo "Checking OpenTofu security..."
tfsec_args=("$DEVENV_ROOT")
for path in .git .devenv .direnv .terraform node_modules result; do
	tfsec_args+=(--exclude-path "$path")
done
tfsec "${tfsec_args[@]}"
echo "tfsec passed."
